### ISSUE TITLE
Site Clean Up

### ISSUE THREAD

**Issue by Gallelee** [lucylee-412/collab-workshop#13]
-Change Favicons

-Polish the Header( fix navbar links and text placemente)

-Brainstorm a new slogan

-Fix precautions grid placement

**Comment by lucylee-412** [comment]
**Additional bug:**

Dynamic sizing issues, see attached screenshot:
![image](https://user-images.githubusercontent.com/5422566/148307777-6a88ad7f-7157-4a3b-8c21-655bc1013a50.png)

**Comment by lucylee-412** [comment]
Update: "Fixed" grid-gap for \#precautions and adjusted font sizes throughout

**Comment by lucylee-412** [comment]
**Update:** Fixed scaling issues introduced by the \#precautions grid, and adjusted margin and width ratios in conjunction with the repeat(auto-fit) property. Set initial and maximum scale of viewport to 1 for good measure (did not see any obvious changes).

Minor change to slogan to match the color of the headings. I plan on using black as hover color for navigation.

**Comment by Gallelee** [comment]
Update - Added the new favicon

**Comment by AdaMaldonado** [comment]
Update: Created new slogan "Spread Facts, Not Fear" in which everyone agreed upon

**Comment by AdaMaldonado** [comment]
Immediate design issues fixed!
