### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by lucylee-412** [lucylee-412/collab-workshop#2]
**Task:** Brainstorm potential designs for website.

Our tentative topic will be on COVID-19 precautions, so have that in mind for your design.

- Color scheme (HEX or RGB values)
- Page content (What should go on index.html, subpage-1.html, subpage-2.html*, ... )
- Favicon

*Number of subpages is dependent on the final design.

**Comment by lucylee-412** [comment]
## **Submitting my wireframe design:**
![Wireframe](https://user-images.githubusercontent.com/5422566/148249371-7640677c-17dd-4b56-9d4b-e2530f990199.png)

### **Hex codes used:**
- **Navigation:**
  - Base: \#88C6ED
  - Main text: \#1984C7
  - Selected page: \#FAFAFA
- **Body:**
  - Background color: \#FAFAFA
  - Heading 1: \#88C6ED
  - Heading 3: \#0A314A
  - Text: \#104B70

Colors not final.
Because the topic of COVID-19 usually brings anxiety, I decided on a blue palette to instill a feeling of calm and peace in the visitor.

@AdaMaldonado @Gallelee
**Please submit your designs as well so that we can come together and vote on a final design to work with.**

**Comment by AdaMaldonado** [comment]
![image](https://user-images.githubusercontent.com/34352705/148265807-c4440366-bb7b-4062-a002-ca7da0b76aed.png)

This is the idea had for one of the pages, I have not coded it yet and used a word document to construct the page.

Hex Values: 
#DAE3f3 (light blue color) #ED7D31 (orange color) #4472C$ (dark blue color) #FFFFFF (white) #000000 (black)

**Comment by Gallelee** [comment]
Link to my figma with the design
https://www.figma.com/file/XX47cKRL5rYIHsAezEmRNn/collab-workshop?node-id=0%3A1

**Comment by lucylee-412** [comment]
I think @Gallelee's design is the cleanest and meets the requirement of having a "modern" web design. Let's go with that.
I'd prefer to change the color of the banner to a more blue value rather than the current aqua value, but we can leave that for finishing touches.

**Comment by lucylee-412** [comment]
Forgot to close this issue earlier. Group agreed on going with Gallelee's design (Ada can add Figma to her arsenal of sitebuilding tools now!), and Ada and Gallelee immediately set off to build the foundation for the HTML and CSS required; thanks.
